---
- hosts: master2
  remote_user: master-2
  gather_facts: no
  tasks:
    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /home/master-2/my-app-deployment.yaml

    - name: Apply Kubernetes Service
      command: kubectl apply -f /home/master-2/my-app-service.yaml --validate=false

    - name: Force Kubernetes to pull the latest Docker image
      command: kubectl rollout restart deployment/my-app

    - name: Wait for Kubernetes rollout status
      command: kubectl rollout status deployment/my-app
